#!/bin/sh

# Load config
#
# --- Example Config File (/home/user/.config/zi_dropbox) ---
#
# TOKEN="INSERT YOUR DROPBOX TOKEN HERE"
# DIRECTORY="dropboxApp"
# # DIRECTORY -> "/Dropbox/Apps/<dropbox_app_name>/$DIRECTORY/"

CONF_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/zi_dropbox"
[ -e $CONF_FILE ] && source "$CONF_FILE" || exit 1

# Get file from argument
[ -z "$1" ] && echo "Usage: dropbox [filename]" && exit 1
LOCAL="$1" 
[ ! -e $LOCAL ] && echo "File called $LOCAL not Found!" && exit 1
FILENAME="$(basename $LOCAL)"
# Name of the file that will be upload to Dropbox (can be set with an argument)
[ -n "$2" ] && DB_FILENAME=$2 || DB_FILENAME="$(date "+%Y-%m-%d")-$FILENAME"

LOG_DIR="${XDG_DATA_HOME:-$HOME/local/share}/zi_dropbox" 
[ ! -d $LOG_DIR ] && mkdir $LOG_DIR

# Upload to dropbox using cURL
# DISCLAIMER: Dropbox token is required!
(curl -X POST https://content.dropboxapi.com/2/files/upload \
    --silent \
    --header "Authorization: Bearer $TOKEN" \
    --header "Dropbox-API-Arg: {\"path\": \"/$DIRECTORY/$DB_FILENAME\",\"mode\": \"add\",\"autorename\": true,\"mute\": false,\"strict_conflict\": false}" \
    --header "Content-Type: application/octet-stream" \
    --data-binary @$LOCAL >> $LOG_DIR/output.txt) && echo "Succesfully uploaded $FILENAME" || echo "An error occurred!"
