#!/bin/sh

# -=- Simple Dropbox Uploader -=-
# Created because my lecturer force me to use Dropbox for some reason
# Requirements: jq

# Load config
#
# --- Example Config File (/home/user/.config/zi_dropbox) ---
#
# TOKEN="INSERT YOUR DROPBOX TOKEN HERE"
# DIRECTORY="dropboxApp"
# # DIRECTORY -> "/Dropbox/Apps/<dropbox_app_name>/$DIRECTORY/"
CONF_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/zi_dropbox"
[ -e $CONF_FILE ] && . "$CONF_FILE" || exit 1

# Error stuff (and instruction on how to use this script)
err()
{
	echo "Usage: dropbox [OPTION...] [FILE]

Options:
  -h		show this message
  -n		change upload name
  -s		share file" && exit 1;
}

# Get flags (options)
while getopts "hn:s" opt; do
    case "${opt}" in
	h) err ;;
        n) DB_FILENAME="${OPTARG}";;
	s) SHARE=1 ;;
        *) ;;
    esac
done

shift $((OPTIND - 1))

# Get file from argument
[ -z "$@" ] && err
LOCAL="$@"
[ ! -e "$LOCAL" ] && echo "File called $LOCAL not Found!" && exit 1
FILENAME="$(basename "$LOCAL")"

# Log
# LOG_DIR="${XDG_DATA_HOME:-$HOME/local/share}/zi_dropbox" 
# [ ! -d $LOG_DIR ] && mkdir $LOG_DIR

# Upload to dropbox using cURL
# DISCLAIMER: Dropbox token is required!
RESULT=$(curl -X POST https://content.dropboxapi.com/2/files/upload \
    --silent \
    --header "Authorization: Bearer $TOKEN" \
    --header "Dropbox-API-Arg: {\"path\": \"/$DIRECTORY/${DB_FILENAME:-$(date "+%Y-%m-%d")-$FILENAME}\",\"mode\": \"add\",\"autorename\": true,\"mute\": false,\"strict_conflict\": false}" \
    --header "Content-Type: application/octet-stream" \
    --data-binary @"$LOCAL")
[ "$(echo $RESULT | jq .error)" = "null" ] && echo "Succesfully uploaded $FILENAME" || echo "An error occurred!" && exit 1

# Share file then print the url
[ ${SHARE:-0} -lt 1 ] && exit 0
curl -X POST https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings \
	--silent \
	--header "Authorization: Bearer $TOKEN" \
	--header "Content-Type: application/json" \
	--data "{\"path\": $(echo $RESULT | jq .path_display),\"settings\": {\"requested_visibility\": \"public\",\"audience\": \"public\",\"access\": \"viewer\"}}" | printf "Shared link: %s\n" $(jq -Mr .url)
