#!/bin/zsh

status=$(waydroid status | grep Session | sed -n 's/^Session:\t//p')

bind() {
	sleep 10
	xtmapper-bind
}

[ $status = "STOPPED" ] && { echo "Please run 'waydroid session start' first!"; exit 1; }

swww kill 2>/dev/null && \
gamemoderun waydroid show-full-ui && bind
